#include <stdio.h>
long long hailstone(long long x)//输入x，x不等于1时输出x后一项，返回x的后一项。x等于1时输出1，返回1.
{
	if (x != 1)
	{
		if (x % 2)//奇数
			x = 3 * x + 1;
		else x /= 2;
		printf("%lld",x);
		return x;
	}
	else 
	{
		printf("1");
		return 1;
	}
}
int main()
{
	int n;//计数器
	long long x;
	while (scanf("%lld",&x) != EOF)
	{
		n = 1;
		printf("Hailstone generated by %lld:\n", x);
		printf("%lld", x);
		
		while (x != 1)
		{
			putchar(' ');
			x = hailstone(x);
			n++;
		}
		printf("\nNumber of hailstone generated:%d\n\n", n);
	}
	return 0;
}